make sure CUDA_INSTALL_PATH points to a valid directory and that "which" can find nvcc
[git-p4: depot-paths = "//depot/gpgpu_sim_research/fermi/distribution/": change = 13084]

diff --git a/setup_environment b/setup_environment
--- a/setup_environment
+++ b/setup_environment
@@ -4,6 +4,19 @@ if [ ! -n "$CUDA_INSTALL_PATH" ]; then
 	echo "ERROR ** Install CUDA Toolkit and set CUDA_INSTALL_PATH.";
 	return;
 fi
+if [ ! -d "$CUDA_INSTALL_PATH" ]; then
+	echo "ERROR ** CUDA_INSTALL_PATH=$CUDA_INSTALL_PATH invalid (directory does not exist)";
+	return;
+fi
+NVCC_PATH=`which nvcc`;
+if [ $? = 1 ]; then
+	echo "";
+	echo "ERROR ** nvcc (from CUDA Toolkit) was not found in PATH but required to build GPGPU-Sim.";
+	echo "         Try adding $CUDA_INSTALL_PATH/bin/ to your PATH environment variable.";
+	echo "         Please also be sure to read the README file if you have not done so.";
+	echo "";
+	return;
+fi
 
 # to run the debug build of GPGPU-Sim run:
 # source setup_environment debug
