move check for nvcc after we set PATH
[git-p4: depot-paths = "//depot/gpgpu_sim_research/fermi/distribution/": change = 13085]

diff --git a/setup_environment b/setup_environment
--- a/setup_environment
+++ b/setup_environment
@@ -8,15 +8,6 @@ if [ ! -d "$CUDA_INSTALL_PATH" ]; then
 	echo "ERROR ** CUDA_INSTALL_PATH=$CUDA_INSTALL_PATH invalid (directory does not exist)";
 	return;
 fi
-NVCC_PATH=`which nvcc`;
-if [ $? = 1 ]; then
-	echo "";
-	echo "ERROR ** nvcc (from CUDA Toolkit) was not found in PATH but required to build GPGPU-Sim.";
-	echo "         Try adding $CUDA_INSTALL_PATH/bin/ to your PATH environment variable.";
-	echo "         Please also be sure to read the README file if you have not done so.";
-	echo "";
-	return;
-fi
 
 # to run the debug build of GPGPU-Sim run:
 # source setup_environment debug
@@ -53,6 +44,16 @@ export LD_LIBRARY_PATH=`echo $LD_LIBRARY_PATH | sed -re 's/.*gpgpu_sim.*(release
 export LD_LIBRARY_PATH=$GPGPUSIM_ROOT/lib/$GPGPUSIM_CONFIG:$LD_LIBRARY_PATH
 export PATH=`echo $PATH | sed "s#$GPGPUSIM_ROOT/bin:$CUDA_INSTALL_PATH/bin:##"`
 export PATH=$GPGPUSIM_ROOT/bin:$CUDA_INSTALL_PATH/bin:$PATH
+
+NVCC_PATH=`which nvcc`;
+if [ $? = 1 ]; then
+	echo "";
+	echo "ERROR ** nvcc (from CUDA Toolkit) was not found in PATH but required to build GPGPU-Sim.";
+	echo "         Try adding $CUDA_INSTALL_PATH/bin/ to your PATH environment variable.";
+	echo "         Please also be sure to read the README file if you have not done so.";
+	echo "";
+	return;
+fi
 
 # The following sets OPENCL_REMOTE_GPU_HOST which is used by GPGPU-Sim to
 # SSH to remote node to generate PTX for OpenCL kernels when running on 
